name: location_tracker
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^11.0.0
  another_flushbar: ^1.12.30
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.1.0
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  google_maps_flutter: ^2.5.3
  shimmer: ^3.0.0
  connectivity_plus: ^5.0.2
  flutter_screenutil: ^5.9.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  hive: ^2.2.3
  path_provider: ^2.1.3
  hive_flutter: ^1.1.0
  bloc_test: ^9.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/fonts/

  fonts:
     - family: Manrope
       fonts:
         - asset: assets/fonts/Manrope-Bold.ttf
         - asset: assets/fonts/Manrope-SemiBold.ttf
         - asset: assets/fonts/Manrope-ExtraBold.ttf
         - asset: assets/fonts/Manrope-ExtraLight.ttf
         - asset: assets/fonts/Manrope-Light.ttf
         - asset: assets/fonts/Manrope-Medium.ttf
         - asset: assets/fonts/Manrope-Regular.ttf
